### PR TITLE
Update Microsoft Word Shortcuts.md

### PR DESCRIPTION
**Pull request by Vani177**
I've added one shortcut ("Open the Styles Pane"), updated the last change I committed. 
Kindly add label for hacktoberfest-accepted if you merge this branch.
Thanks!

### CODE REVIEW

**Comment by AyushSarode** [comment]
Nice work!

**Comment by AnshSinghSonkhia** [comment]
Good Work @Vani177

**Comment by Vani177** [comment]
thank you sm, glad to contribute!

**Comment by AnshSinghSonkhia** [comment]
Thanks for contributing Vani.
Let's Connect: [LinkedIn](https://www.linkedin.com/in/anshsinghsonkhia/)

**Pull request merged**
