### PR TITLE
Update Gmail Keyboard Shortcuts.md

### PR DESCRIPTION
**Pull request by stefanoleggio**

### CODE REVIEW

**Comment by stefanoleggio** [comment]
Hello! When you will accept this pull request I will pull the Excel Keyboard Shortcuts!

**Comment by AnshSinghSonkhia** [comment]
@stefanoleggio, Are you participating in hacktoberfest 2022?
So, I will merge them tomorrow.

**Comment by stefanoleggio** [comment]
Yes I am participating. But I think they are already valid (the website is already counting the pull requests)

**Comment by AnshSinghSonkhia** [comment]
> Yes I am participating. But I think they are already valid (the website is already counting the pull requests)

Probably, because you're from Italy.
I'm currently in India. I will merge your PR tomorrow Morning!

**Pull request merged**
