### PR TITLE
Added Global find shortcut

### PR DESCRIPTION
**Pull request by RachitGarg-12**
Added Global Find Shortcut of vs code. This shortcut is most useful for developers

### CODE REVIEW

**Comment by RachitGarg-12** [comment]
issue :#73   solved

**Comment by AnshSinghSonkhia** [comment]
@RachitGarg-12, You are not allowed to make a different file for VS Code.
DO your changes of this PR & the last one in the existing VSCode.md file.

**Comment by RachitGarg-12** [comment]
ok

**Comment by AnshSinghSonkhia** [comment]
Is there anything left or may I merge this PR?

**Comment by RachitGarg-12** [comment]
no , everything done

**Comment by RachitGarg-12** [comment]
I have done everything needed . Please merge my PR

**Pull request closed without merging**
